### ISSUE TITLE
`Global` support for `Components.yml`

### ISSUE THREAD

**Issue by prplwtf** [BlueprintFramework/framework#57]
### Scope

Extension API

### Explanation

(https://discord.com/channels/1063548024825057451/1094955970100203581/1296108726188507210)

```yaml
Global:
  BeforeContent: "" # component added at the top of the page, always
  AfterContent: "" # component added at the end of the page, always
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
